select 
  count(distinct jb.member_id) as members_job_onboarding,
  count(distinct case when (jb.posting_method = 'AutoEdited' or jav.memberid is not null) then jb.member_id end) as members_edit_job_onboarding,
  (( count(distinct case when (jb.posting_method = 'AutoEdited' or jav.memberid is not null) then jb.member_id end) / count(distinct jb.member_id) )*100) as '%_members_edit_job_onboarding' 

from intl.job jb
left join  (
            select 
              je.countrycode, je.memberid, je.jobid, jv.attribute_key, je.datecreated
            from intl.hive_event je
            join intl.JOB_ATTRIBUTE_VALUE jv  on je.jobid = jv.job_id and je.countrycode = jv.country_code and date(je.datecreated) = date(jv.last_updated)
                                             and jv.attribute_key in ('jobNumberOfDays','jobRecurringBase_biweekly','jobRecurringBase_day','jobRecurringBase_month', 'jobRecurringBase_week', 'jobTimes')  
            where name = 'Edit'
              and itemType = 'Job'
              and action = 'AutoEdited'
              and memberSearchStatus = 'Approved'
              and year = 2023
            group by 1,2,3,4,5
                                                      ) jav on jb.member_id = jav.memberid and jb.country_code = jav.countrycode and jb.id = jav.jobid and date(jb.date_created) = date(jav.datecreated)
where 1
  and jb.posting_method in ('AutoGenerated', 'AutoEdited')
  and jb.search_status = 'Approved'
  and year(jb.date_created) = 2023
